Repository SwArch-2025-1-2A/frontend, pull requests merged in 2025-05, with the labels that each got.

#1 Initialize project from template
  .github/FUNDING.yml
  .github/dependabot.yml
  .github/workflows/main.yml
  .npmrc
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  eslint.config.mjs
  next-env.d.ts
  next.config.ts
  package-lock.json
  package.json
  playwright.config.ts
  playwright/smoke.test.ts
  postcss.config.js
  prisma/migrations/20211019164222_init/migration.sql
  prisma/migrations/20220307124425_non_unique_timestamps/migration.sql
  prisma/migrations/20220918091608_pagination/migration.sql
  prisma/migrations/20220918134120_revert/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  public/favicon.ico
  public/vercel.svg
  sandbox.config.json
  src/components/DefaultLayout.tsx
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/api/trpc/[trpc].ts
  src/pages/index.tsx
  src/pages/post/[id].tsx
  src/server/context.ts
  src/server/env.ts
  src/server/prisma.ts
  src/server/routers/_app.ts
  src/server/routers/post.test.ts
  src/server/routers/post.ts
  src/server/trpc.ts
  src/styles/globals.css
  src/utils/transformer.ts
  src/utils/trpc.ts
  tailwind.config.ts
  tsconfig.json
  vitest.config.ts
Labels: documentation, enhancement

#4 New initialization
  .github/FUNDING.yml
  .github/dependabot.yml
  .github/workflows/main.yml
  .npmrc
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  eslint.config.js
  eslint.config.mjs
  next-env.d.ts
  next.config.ts
  package-lock.json
  package.json
  playwright.config.ts
  playwright/smoke.test.ts
  postcss.config.js
  prettier.config.js
  prisma/migrations/20211019164222_init/migration.sql
  prisma/migrations/20220307124425_non_unique_timestamps/migration.sql
  prisma/migrations/20220918091608_pagination/migration.sql
  prisma/migrations/20220918134120_revert/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  prisma/seed.ts
  public/favicon.ico
  public/vercel.svg
  sandbox.config.json
  src/app/_components/post.tsx
  src/app/api/trpc/[trpc]/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/DefaultLayout.tsx
  src/env.ts
  src/pages/404.tsx
  src/pages/_app.tsx
  src/pages/api/trpc/[trpc].ts
  src/pages/index.tsx
  src/pages/post/[id].tsx
  src/server/api/root.ts
  src/server/api/routers/post.ts
  src/server/api/trpc.ts
  src/server/context.ts
  src/server/env.ts
  src/server/prisma.ts
  src/server/routers/_app.ts
  src/server/routers/post.test.ts
  src/server/routers/post.ts
  src/server/trpc.ts
  src/styles/globals.css
  src/trpc/query-client.ts
  src/trpc/react.tsx
  src/trpc/server.ts
  src/utils/transformer.ts
  src/utils/trpc.ts
  tailwind.config.ts
  tsconfig.json
  vitest.config.ts
Labels: documentation, dependencies

#6 Containerize the project with Docker
  .dockerignore
  Dockerfile
  README.md
Labels: enhancement, dependencies

#7 Quality of life improvements for `Docker`
  .dockerignore
  .prodignore
  Dockerfile
  README.md
Labels: documentation, enhancement, Docker

#9 Create table of contents
  README.md
Labels: documentation

#13 Create docker compose
  .dockerignore
  .env.example
  .prodignore
  docker-compose.yml
Labels: Docker

#15 Fix arguments
  .env.example
  docker-compose.yml
  src/graphql/apolloClient.ts
Labels: bug, Docker
